name: Update levels.json

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Crear archivo
        run: |
          echo "No actualizar todavía"

      - name: Guardar cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add levels.json
          git commit -m "Update levels.json" || exit 0
          git push
